# Generated by Django 5.1.2 on 2024-10-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0004_delete_country"),
        ("users", "0004_remove_address_billing_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(
                upload_to="shops/books/%Y/%m/%d"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="audiobook_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="USD da kiritamiz",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(blank=True, to="users.author"),
        ),
        migrations.AlterField(
            model_name="book",
            name="ebook_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="USD da kiritamiz",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="new_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="USD da kiritamiz",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="used_good_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="USD da kiritamiz",
                max_digits=6,
                null=True,
            ),
        ),
    ]
