# Generated by Django 5.1.2 on 2024-10-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0006_alter_book_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="reviews_count",
            field=models.PositiveIntegerField(db_default=0, editable=False),
        ),
    ]
