# Generated by Django 5.1.2 on 2024-10-16 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_country_alter_address_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="address",
            name="shipping_address",
        ),
        migrations.AddField(
            model_name="user",
            name="billing_address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="billing_user",
                to="users.address",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shipping_address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="shipping_user",
                to="users.address",
            ),
        ),
    ]
